# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: goreleaser [dry run]

on:
  push:
    branches: [ "master" , "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Release (dry run)
      run: make release-dry-run
#    - name: Test
#      run: go test -v ./...
