name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - run: git fetch --prune --unshallow

      - name: set up golang
        uses: actions/setup-go@v4

      - name: release dry run
        run: make release-dry-run

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env

      - name: release publish
        run: make release